fix: version definition for google provider
Before the fix we were getting the error:

Error: Unsuitable value type

On .terraform/modules/terraform-google-cloud-run/versions.tf line 5:
Unsuitable value: string required